# Generated by Django 4.1.3 on 2022-11-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyogi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('clear', models.CharField(max_length=255)),
                ('clear_time', models.IntegerField()),
            ],
        ),
    ]
