# Generated by Django 4.1.3 on 2022-11-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyogi', '0005_alter_total_clear_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='clear_time',
            field=models.IntegerField(null=True),
        ),
    ]
