# Generated by Django 4.1.3 on 2022-11-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyogi', '0006_alter_total_clear_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='clear_time',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
