# Generated by Django 4.1.3 on 2022-12-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyogi', '0007_alter_total_clear_time'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='total',
            constraint=models.UniqueConstraint(fields=('name', 'number', 'clear'), name='unique_total'),
        ),
    ]
