# Generated by Django 4.1.3 on 2023-01-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyogi', '0008_total_unique_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='resets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('number', models.IntegerField(null=True)),
                ('save_time', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
