# Generated by Django 4.1.3 on 2023-01-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyogi', '0009_resets'),
    ]

    operations = [
        migrations.CreateModel(
            name='anker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anktext', models.CharField(max_length=255)),
            ],
        ),
    ]
